# -*- coding: utf-8 -*-
"""tdl-miniproject-hindi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T7is4haO6sSQvrnZeu-il9KLCDmX_87j

**TDL Mini Project — Cross-Lingual NER: Western-to-Hindi Performance Gap Analysis**

**Design:** 4 multilingual models × 2 experiments

- **Exp 1:** Train on English WikiANN → zero-shot test on Hindi (measures raw cross-lingual transfer)
- **Exp 2:** Load Exp 1 best checkpoint → fine-tune on Hindi (measures warm-start adaptation gain)

**Research question:** Can multilingual models transfer NER knowledge to Hindi without seeing Hindi data, and how much does English warm-starting help Hindi adaptation?

*Automated — runs all 4 models back to back, no manual changes needed.*
"""

# ── CELL 0 — Install Dependencies ─────────────────────────────────────────────
!pip install transformers datasets seqeval accelerate -q

# ── CELL 1 — Hugging Face Authentication ──────────────────────────────────────
# Required for ai4bharat/indic-bert (gated repo).
# Setup: Click 🔑 key icon in Colab sidebar → Add secret → Name: HF_TOKEN → paste token
from kaggle_secrets import UserSecretsClient
from huggingface_hub import login

try:
    user_secrets = UserSecretsClient()
    hf_token = user_secrets.get_secret("HF_TOKEN")

    login(token=hf_token, add_to_git_credential=False)
    print("HuggingFace login successful.")

except Exception as e:
    print(f"Login skipped: {e}")
    print("Only needed for ai4bharat/indic-bert")

# ── CELL 2 — Imports ───────────────────────────────────────────────────────────
import os
import shutil
import warnings
import numpy as np
import torch
import pandas as pd
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification,
)
from seqeval.metrics import classification_report

print("PyTorch version:", torch.__version__)
print("GPU available:  ", torch.cuda.is_available())

# ── CELL 3 — Config ────────────────────────────────────────────────────────────
# All 6 models run automatically in order.
# Hyperparameters are fixed across all models for fair comparison.

MODELS = [
    # ── General multilingual baselines ────────────────────────────────────────
    "bert-base-multilingual-cased",           # mBERT: WordPiece, 104 langs, low Hindi exposure
    "distilbert-base-multilingual-cased",     # Distil-mBERT: 40% smaller mBERT, WordPiece
    "xlm-roberta-base",                       # XLM-R base: SentencePiece, 100 langs, CC-100
    # ── Indic-specialised models ───────────────────────────────────────────────
    "google/muril-base-cased",                # MuRIL: WordPiece, 17 Indian langs + transliteration
    "ai4bharat/indic-bert",                   # IndicBERT v1: ALBERT-based, SentencePiece, 12 Indic langs — needs HF_TOKEN
    "ai4bharat/IndicBERTv2-MLM-Sam-TLM",      # IndicBERTv2: BERT-based, WordPiece, improved Indic coverage
]

MAX_LEN    = 128
BATCH_SIZE = 16    # default for all models
EPOCHS     = 3
LR         = 5e-5

BATCH_SIZE_OVERRIDE = {}  # no overrides needed for current model set

# Model metadata for analysis
# hindi_exposure: subjective tier — high/medium/low based on pre-training corpus composition
# hindi_score: rough 0-1 scale for correlation analysis
model_meta = {
    "bert-base-multilingual-cased":        {"params": 110e6, "hindi_exposure": "low",    "hindi_score": 0.2, "tokenizer_type": "WordPiece",    "architecture": "BERT"},
    "distilbert-base-multilingual-cased":  {"params":  66e6, "hindi_exposure": "low",    "hindi_score": 0.2, "tokenizer_type": "WordPiece",    "architecture": "DistilBERT"},
    "xlm-roberta-base":                    {"params": 125e6, "hindi_exposure": "medium", "hindi_score": 0.5, "tokenizer_type": "SentencePiece", "architecture": "RoBERTa"},
    "google/muril-base-cased":             {"params": 236e6, "hindi_exposure": "high",   "hindi_score": 0.9, "tokenizer_type": "WordPiece",    "architecture": "BERT"},
    "ai4bharat/indic-bert":                {"params":  12e6, "hindi_exposure": "high",   "hindi_score": 0.9, "tokenizer_type": "SentencePiece", "architecture": "ALBERT"},
    "ai4bharat/IndicBERTv2-MLM-Sam-TLM":   {"params": 278e6, "hindi_exposure": "high",   "hindi_score": 0.9, "tokenizer_type": "WordPiece",    "architecture": "BERT"},
}

print(f"Models to run: {len(MODELS)}")
for m in MODELS:
    meta = model_meta[m]
    bs   = BATCH_SIZE_OVERRIDE.get(m, BATCH_SIZE)
    print(f"  → {m:50s} | arch={meta['architecture']:10s} | tok={meta['tokenizer_type']:12s} | batch={bs}")

# ── CELL 4 — Load Datasets ─────────────────────────────────────────────────────
# WikiANN: Wikipedia-based NER. English and Hindi share identical label space.
# Labels: O, B-PER, I-PER, B-ORG, I-ORG, B-LOC, I-LOC — no remapping needed.

conll = load_dataset("wikiann", "en")  # English → Experiment 1 training
hiner = load_dataset("wikiann", "hi")  # Hindi   → Experiment 1 zero-shot test + Experiment 2

label_names = conll["train"].features["ner_tags"].feature.names
id2label    = {i: l for i, l in enumerate(label_names)}
label2id    = {l: i for i, l in id2label.items()}

print("Labels:", label_names)
print(f"English train: {len(conll['train'])} | Hindi train: {len(hiner['train'])} | Hindi test: {len(hiner['test'])}")

# ── CELL 5 — Helper Functions ──────────────────────────────────────────────────

def compute_fertility(tokenizer, dataset):
    """
    Token fertility = average subword tokens per Hindi word.
    1.0 = model knows every Hindi word perfectly.
    Higher = model fragments Hindi words more = weaker Hindi understanding.
    """
    total_words = total_subwords = 0
    for example in dataset:
        words           = example["tokens"]
        total_words    += len(words)
        total_subwords += len(
            tokenizer(words, is_split_into_words=True,
                      add_special_tokens=False)["input_ids"]
        )
    return total_subwords / total_words


def tokenize_and_align_labels(examples, tokenizer, label_all_tokens=False):
    """
    Aligns NER labels (per word) to subword tokens:
      - First subword of each word → real label
      - Continuation subwords      → -100 (ignored by loss and eval)
      - Special tokens [CLS]/[SEP] → -100
    """
    tokenized = tokenizer(
        examples["tokens"],
        truncation=True,
        max_length=MAX_LEN,
        is_split_into_words=True,
    )
    aligned_labels = []
    for i, label_seq in enumerate(examples["ner_tags"]):
        word_ids     = tokenized.word_ids(batch_index=i)
        prev_word_id = None
        label_ids    = []
        for word_id in word_ids:
            if word_id is None:
                label_ids.append(-100)
            elif word_id != prev_word_id:
                label_ids.append(label_seq[word_id])
            else:
                label_ids.append(label_seq[word_id] if label_all_tokens else -100)
            prev_word_id = word_id
        aligned_labels.append(label_ids)
    tokenized["labels"] = aligned_labels
    return tokenized


def make_compute_metrics(label_names):
    """
    seqeval-based metrics. Scores at entity span level (entire span must be correct).
    Also returns per-entity F1 for PER, ORG, LOC.
    """
    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        predictions    = np.argmax(logits, axis=-1)
        true_labels = [
            [label_names[l] for l in row if l != -100]
            for row in labels
        ]
        true_preds = [
            [label_names[p] for p, l in zip(pred_row, label_row) if l != -100]
            for pred_row, label_row in zip(predictions, labels)
        ]
        report  = classification_report(true_labels, true_preds, output_dict=True)
        metrics = {
            "f1":        report["micro avg"]["f1-score"],
            "precision": report["micro avg"]["precision"],
            "recall":    report["micro avg"]["recall"],
        }
        for entity in ["PER", "ORG", "LOC"]:
            if entity in report:
                metrics[f"f1_{entity}"] = report[entity]["f1-score"]
        return metrics
    return compute_metrics


def make_trainer(model, args, train_ds, eval_ds, tokenizer):
    return Trainer(
        model=model,
        args=args,
        train_dataset=train_ds,
        eval_dataset=eval_ds,
        processing_class=tokenizer,
        data_collator=DataCollatorForTokenClassification(tokenizer),
        compute_metrics=make_compute_metrics(label_names),
    )


def clear_checkpoints(run_name):
    for prefix in ["exp1_", "exp2_"]:
        d = f"./{prefix}{run_name}"
        if os.path.exists(d):
            shutil.rmtree(d)

# ── CELL 6 — MAIN LOOP: Run All 6 Models ──────────────────────────────────────
# Experimental design:
#
#   Exp 1 — Cross-lingual zero-shot transfer
#            Fresh pretrained model → train on English WikiANN → zero-shot test on Hindi
#            Measures: how much NER knowledge transfers across languages without Hindi data
#
#   Exp 2 — Cross-lingual warm-start adaptation
#            Loads BEST CHECKPOINT from Exp 1 (English-trained weights) → fine-tune on Hindi
#            Measures: how much English NER warm-starting helps Hindi adaptation
#
#   Gap    = fine_f1 - zero_f1
#            Represents the adaptation gain ON TOP OF cross-lingual transfer.
#            NOT a fresh-from-scratch Hindi baseline — that would conflate two effects.
#
# This design directly answers: "Does English NER training provide a useful warm-start
# for Hindi adaptation, and does this vary by model architecture / tokenizer type?"

warnings.filterwarnings("ignore", message=".*OrderedVocab.*")
warnings.filterwarnings("ignore", message=".*vocabulary could be corrupted.*")

all_results = []

for MODEL_NAME in MODELS:
    run_name      = MODEL_NAME.split("/")[-1]
    effective_batch = BATCH_SIZE_OVERRIDE.get(MODEL_NAME, BATCH_SIZE)

    print("\n" + "█" * 60)
    print(f"  MODEL: {MODEL_NAME}")
    print(f"  Batch size: {effective_batch}  (override={MODEL_NAME in BATCH_SIZE_OVERRIDE})")
    print("█" * 60)

    # ── Load tokenizer ────────────────────────────────────────────────────────
    # IndicBERT v1 (ALBERT/SentencePiece) and XLM-R (RoBERTa/SentencePiece) load
    # as non-BERT tokenizers — this is expected and handled correctly by word_ids().
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    print(f"Tokenizer: {type(tokenizer).__name__}")

    # ── Token Fertility on Hindi test set ─────────────────────────────────────
    # Fertility = avg subword tokens per Hindi word.
    # Lower = tokenizer knows Hindi better (less fragmentation).
    fertility_score = compute_fertility(tokenizer, hiner["test"])
    print(f"Fertility: {fertility_score:.4f}  (1.0=perfect, higher=more fragmentation)")

    # ── Tokenize datasets (fresh for each model — tokenizer changes) ──────────
    def align(examples):
        return tokenize_and_align_labels(examples, tokenizer)

    conll_tokenized = conll.map(align, batched=True, remove_columns=conll["train"].column_names)
    hiner_tokenized = hiner.map(align, batched=True, remove_columns=hiner["train"].column_names)
    hiner_test_tok  = hiner["test"].map(align, batched=True, remove_columns=hiner["test"].column_names)

    # ─────────────────────────────────────────────────────────────────────────
    # EXPERIMENT 1 — Train on English, Zero-Shot Test on Hindi
    # ─────────────────────────────────────────────────────────────────────────
    print(f"\n{'='*60}")
    print(f"EXP 1 — Training on English [{run_name}]")
    print(f"{'='*60}")

    exp1_dir = f"./exp1_{run_name}"

    model_exp1 = AutoModelForTokenClassification.from_pretrained(
        MODEL_NAME,
        num_labels=len(label_names),
        id2label=id2label,
        label2id=label2id,
        ignore_mismatched_sizes=True,
    )

    args_exp1 = TrainingArguments(
        output_dir=exp1_dir,
        num_train_epochs=EPOCHS,
        learning_rate=LR,
        per_device_train_batch_size=effective_batch,
        per_device_eval_batch_size=effective_batch,
        eval_strategy="epoch",
        save_strategy="epoch",
        save_total_limit=1,          # keep only best checkpoint to save disk
        load_best_model_at_end=True,
        metric_for_best_model="f1",
        logging_steps=50,
        report_to="none",
    )

    trainer_exp1 = make_trainer(
        model_exp1, args_exp1,
        conll_tokenized["train"], conll_tokenized["validation"],
        tokenizer,
    )
    trainer_exp1.train()

    print(f"\n{'='*60}")
    print(f"EXP 1 — Zero-Shot Eval on Hindi [{run_name}]")
    print(f"{'='*60}")
    results_exp1 = trainer_exp1.evaluate(hiner_test_tok)
    print(results_exp1)

    # Save trainer state so we can find the best checkpoint path
    exp1_best_ckpt = trainer_exp1.state.best_model_checkpoint
    print(f"Best Exp 1 checkpoint: {exp1_best_ckpt}")

    # Free Exp 1 model from GPU memory before loading Exp 2
    del model_exp1, trainer_exp1
    torch.cuda.empty_cache()

    # ─────────────────────────────────────────────────────────────────────────
    # EXPERIMENT 2 — Warm-Start from Exp 1 Checkpoint, Fine-tune on Hindi
    # ─────────────────────────────────────────────────────────────────────────
    # We load the BEST checkpoint saved during Exp 1 (English-trained weights).
    # This is the key design choice: Exp 2 continues cross-lingual adaptation
    # rather than training Hindi from scratch.
    # Scientific justification: measures adaptation gain ON TOP OF transfer,
    # directly quantifying how useful English NER knowledge is as a warm-start.
    # ─────────────────────────────────────────────────────────────────────────
    print(f"\n{'='*60}")
    print(f"EXP 2 — Hindi Fine-tuning from Exp 1 checkpoint [{run_name}]")
    print(f"{'='*60}")

    # Fallback: if trainer.state.best_model_checkpoint is None, find manually
    if exp1_best_ckpt is None or not os.path.exists(exp1_best_ckpt):
        checkpoints = [
            os.path.join(exp1_dir, d)
            for d in os.listdir(exp1_dir)
            if d.startswith("checkpoint")
        ]
        assert len(checkpoints) > 0, f"No checkpoints found in {exp1_dir}"
        exp1_best_ckpt = max(checkpoints, key=os.path.getmtime)
        print(f"Fallback checkpoint resolution: {exp1_best_ckpt}")

    print(f"Loading from: {exp1_best_ckpt}")

    model_exp2 = AutoModelForTokenClassification.from_pretrained(
        exp1_best_ckpt,           # ← English-trained weights, NOT fresh pretrained
        num_labels=len(label_names),
        id2label=id2label,
        label2id=label2id,
        ignore_mismatched_sizes=True,
    )

    args_exp2 = TrainingArguments(
        output_dir=f"./exp2_{run_name}",
        num_train_epochs=EPOCHS,
        learning_rate=LR,
        per_device_train_batch_size=effective_batch,
        per_device_eval_batch_size=effective_batch,
        eval_strategy="epoch",
        save_strategy="epoch",
        save_total_limit=1,
        load_best_model_at_end=True,
        metric_for_best_model="f1",
        logging_steps=50,
        report_to="none",
    )

    trainer_exp2 = make_trainer(
        model_exp2, args_exp2,
        hiner_tokenized["train"], hiner_tokenized["validation"],
        tokenizer,
    )
    trainer_exp2.train()

    print(f"\n{'='*60}")
    print(f"EXP 2 — Test Eval on Hindi [{run_name}]")
    print(f"{'='*60}")
    results_exp2 = trainer_exp2.evaluate(hiner_tokenized["test"])
    print(results_exp2)

    # Verify warm-start worked: Exp 2 epoch-1 loss should be lower than Exp 1 epoch-1 loss
    # (model already has NER knowledge from English training)
    print(f"\n[Warm-start verification]")
    print(f"  Exp 2 epoch-1 train loss: check training logs above")
    print(f"  If lower than Exp 1 epoch-1 loss → warm-start confirmed ✓")

    # Free Exp 2 model from GPU memory
    del model_exp2, trainer_exp2
    torch.cuda.empty_cache()

    # ── Per-model summary ─────────────────────────────────────────────────────
    gap = results_exp2["eval_f1"] - results_exp1["eval_f1"]
    print(f"\n{'='*60}")
    print(f"  SUMMARY — {MODEL_NAME}")
    print(f"{'='*60}")
    print(f"  Fertility:     {fertility_score:.4f}")
    print(f"  Zero-Shot F1:  {results_exp1['eval_f1']:.4f}  (English-trained → Hindi)")
    print(f"  Fine-Tuned F1: {results_exp2['eval_f1']:.4f}  (warm-start → Hindi adapted)")
    print(f"  Gap:           {gap:+.4f}  (adaptation gain from warm-start)")

    # ── Append to results store ───────────────────────────────────────────────
    all_results.append({
        "model":     MODEL_NAME,
        "zero_f1":   results_exp1["eval_f1"],
        "fine_f1":   results_exp2["eval_f1"],
        "fertility": fertility_score,
        "zs_PER":    results_exp1.get("eval_f1_PER", float("nan")),
        "zs_ORG":    results_exp1.get("eval_f1_ORG", float("nan")),
        "zs_LOC":    results_exp1.get("eval_f1_LOC", float("nan")),
        "ft_PER":    results_exp2.get("eval_f1_PER", float("nan")),
        "ft_ORG":    results_exp2.get("eval_f1_ORG", float("nan")),
        "ft_LOC":    results_exp2.get("eval_f1_LOC", float("nan")),
    })
    print(f"  Collected: {len(all_results)} / {len(MODELS)} models done  (batch used: {effective_batch})")

    # Clear exp1 checkpoints to free disk — exp2 checkpoints cleared after final analysis
    clear_checkpoints(run_name)

print("\n" + "█" * 60)
print("  ALL MODELS COMPLETE")
print("█" * 60)

import pandas as pd
pd.DataFrame(all_results).to_csv("ner_results_checkpoint.csv", index=False)
print("Saved 3 models safely.")

# ── CELL 7 — Final Analysis ────────────────────────────────────────────────────
# Run automatically after the loop finishes.
# gap = adaptation gain from warm-starting Exp 2 from Exp 1 English-trained checkpoint
# recovery = fraction of remaining headroom recovered by Hindi fine-tuning

df = pd.DataFrame(all_results)
df["gap"] = df["fine_f1"] - df["zero_f1"]

df["params"]         = df["model"].apply(lambda x: model_meta[x]["params"])
df["tokenizer_type"] = df["model"].apply(lambda x: model_meta[x]["tokenizer_type"])
df["architecture"]   = df["model"].apply(lambda x: model_meta[x]["architecture"])
df["hindi_score"]    = df["model"].apply(lambda x: model_meta[x]["hindi_score"])
df["hindi_exposure"] = df["model"].apply(lambda x: model_meta[x]["hindi_exposure"])

# Derived metrics
df["efficiency"] = df["zero_f1"] / df["params"]                              # zero-shot F1 per parameter
df["recovery"]   = (df["fine_f1"] - df["zero_f1"]) / (1 - df["zero_f1"])    # fraction of remaining headroom (above zero-shot) recovered by warm-start adaptation

# Sanity checks
assert df[["zero_f1", "fine_f1", "fertility"]].isnull().sum().sum() == 0, \
    "Missing values — did all models finish?"
assert (df["zero_f1"].between(0, 1)).all(), "zero_f1 out of [0,1] range"
assert (df["fine_f1"].between(0, 1)).all(), "fine_f1 out of [0,1] range"
assert (df["fertility"] >= 1.0).all(),      "fertility < 1.0 is impossible"
assert len(df) == len(MODELS), f"Expected {len(MODELS)} models, got {len(df)}"
print("All sanity checks passed.")

# Save
df.to_csv("ner_crosslingual_results.csv", index=False)
print("Saved: ner_crosslingual_results.csv")

# Print final table
display_cols = ["model", "architecture", "tokenizer_type", "fertility", "zero_f1", "fine_f1", "gap", "recovery", "hindi_exposure"]
print("\n" + "=" * 90)
print("FINAL RESULTS — sorted by zero-shot F1")
print("=" * 90)
print(df[display_cols].sort_values("zero_f1", ascending=False).to_string(index=False))
print("=" * 90)